# Generated by Django 3.2.25 on 2025-11-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Interview Session', 'verbose_name_plural': 'Interview Sessions'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Resume', 'verbose_name_plural': 'Resumes'},
        ),
    ]
