# Generated by Django 3.2.25 on 2025-11-13 12:12

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20251113_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='current_level',
            field=models.CharField(default='beginner', max_length=50),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='evaluation_flag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='flag_records',
            field=djongo.models.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='recommended_next_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_level',
            field=models.CharField(default='beginner', max_length=50),
        ),
    ]
