# Generated by Django 3.2.25 on 2025-10-25 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20251018_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('hr', 'HR'), ('behavioral', 'Behavioral')], max_length=20)),
                ('text', models.TextField()),
                ('expected_keywords', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('feedback_summary', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('score', models.FloatField(default=0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interviewsession')),
            ],
        ),
    ]
